[colors.bright]
black = "#5b5f71"
blue = "#a0b9d8"
cyan = "#7dc2c7"
green = "#92c47e"
magenta = "#c6aed7"
red = "#fe9f7c"
white = "#f0ecfe"
yellow = "#d2b45f"

[colors.normal]
black = "#2e313d"
blue = "#8296b0"
cyan = "#659ea2"
green = "#76a065"
magenta = "#a18daf"
red = "#cf8164"
white = "#b5b4c9"
yellow = "#ab924c"

[colors.primary]
background = "#191c25"
foreground = "#b5b4c9"

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.offset]
y = 1

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 0.85
startup_mode="Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 8
y = 4
